version: '3.8'

services:
  tomcat-client:
    image: dev/snapshot/tomcat-client:latest
    ports:
      - "8880:8080"
    networks:
      - my-network

  wildfly-server:
    image: dev/snapshot/wildfly-server:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - my-network

networks:
  my-network:
